package basics.p3_classes_objects_interfaces

//toString, equals, and hashCode

class Client(val name: String, val id: Int) {
    override fun toString() = "Client(name=$name, id=$id)"
    //todo: try removing the override here, why the compiler is angry ? ?
    override fun equals(other: Any?): Boolean { // 'Any?' is like java.lang.Object
        return when(other) {
            is Client -> other.id == id && other.name == name
            else -> false
        }
    }
    override fun hashCode(): Int = name.hashCode() * 31 + id
}

fun run() {
    val vlad = Client("Vlad",1)
    println(vlad) //Client(name=Vlad, id=1)

    val anotherVlad = Client("Vlad",1)

    println(
        vlad == anotherVlad // this is compiled to vlad?.equals(anotherVlad)
    // == does not check its the same reference
    )
}


data class TopClient(val name: String, val id: Int)
// has all above and more generated by the compiler
// and copy constructor
// and destructuring declarations  ( we will cover later )
// and component functions  ( we will cover later )